decoder {
  name        =   Heidemann-HX-Extension-Cfg,
  modulation  =   OOK_PWM,
  s           =   332,
  l           =   676,
  g           =   900,
  r           =   7000,
  unique,
  invert,
  repeats     >=   20,
  bits        =   13,
  get         =   battery_ok:@0:{1}:[0x00:1 0x01:0],
  get         =   id:@1:{8}:%d,
  get         =   melody:@9:{4}:%d,
}
